Interns/lhao03/38281 personal delegated permissions
LokiLabs/microsoft-graph-explorer-v4 pull request #13
Opened 2021-06-30 22:24 UTC by lhao03

## Overview

Backlog item to fix the but for Personal accounts.

### Demo

Depends on #12 because it depends on the `permissionModeType` reducer.

### Notes

After #12 is merged, I'll add the condition to switch to DelegatedPersonal or DelegatedWork.

## Testing Instructions

`nvm use 14.0`
`npm install && npm start`

If you open the console you can see the account type. Profile type is either "AAD" or "MSA". 
![image](https://user-images.githubusercontent.com/55033656/124039145-2fda2480-d9b7-11eb-8451-083e1b416a36.png)

2021-06-30 22:25 UTC, lhao03 commented on src/app/services/actions/permissions-action-creator.ts
> +
this will be changed once @12 is merged.

2021-06-30 22:25 UTC, lhao03 commented on src/app/services/actions/profile-action-creators.ts
> +
not tested because it is being called within a function that is already being tested.

2021-07-05 22:24 UTC, ChangshengYan approved these changes

2021-07-05 22:24 UTC, ChangshengYan commented on src/app/services/actions/profile-action-creators.ts
> +  }
nit: semicolon

2021-07-05 22:24 UTC, ChangshengYan commented on src/app/services/actions/profile-action-creators.ts
> +          dispatch(profileTypeSuccess(json.account[0].source.type[0]))
nit: semicolon

2021-07-05 22:24 UTC, ChangshengYan commented on src/app/services/reducers/profile-reducer.ts
> +      return action.response
nit: semicolon

2021-07-05 22:24 UTC, ChangshengYan commented on src/app/services/actions/profile-action-creators.ts
>  import { authenticatedRequest, isImageResponse, parseResponse } from './query-action-creator-util';
looks like the `parseResponse` function is used in multiple places. maybe it's a good time to add some typing for it :)

2021-07-05 22:24 UTC, ChangshengYan commented on src/types/profile.ts
> +import { ACCOUNT_TYPE } from '../app/services/graph-constants';
remove if not used

2021-07-05 23:15 UTC, acchiang commented on src/app/views/authentication/profile/Profile.tsx
> +import { USER_INFO_URL, USER_PICTURE_URL, BETA_USER_INFO_URL, ACCOUNT_TYPE } from '../../../services/graph-constants';
remove ACCOUNT_TYPE since it's not used here :)

2021-07-07 13:48 UTC, AyuAi requested changes
This code will need a rebase when #23 merges into #16; I think I will wait to review the PR until the rebase is complete to make sure the review is up-to-date 👀

2021-07-12 13:26 UTC, lhao03 commented
Closing this PR as the PR against the main repo has been merged: https://github.com/microsoftgraph/microsoft-graph-explorer-v4/pull/1008

2021-07-12 13:26 UTC, closed without merging