mvp-fixes
LokiLabs/microsoft-graph-explorer-v4 pull request #20
Opened 2021-07-05 19:22 UTC by lhao03

based on comments in #16

2021-07-05 19:29 UTC, lhao03 commented
how did you get graph explorer to show in a different language?

2021-07-05 20:09 UTC, AyuAi commented
> how did you get graph explorer to show in a different language?

I just added the locale in the URL; so localhost:3000 became localhost:3000/zh-CN

2021-07-06 13:40 UTC, AyuAi requested changes

2021-07-06 13:40 UTC, AyuAi commented on src/app/views/query-runner/request/permissions/Permission.tsx
> +      || prevProps.permissionModeType !== this.props.permissionModeType) {
```suggestion
        || prevProps.permissionsPanelOpen !== this.props.permissionsPanelOpen
        || prevProps.permissionModeType !== this.props.permissionModeType) {
```
The extra indentation is an intentional formatting for if statements / functions of the like

2021-07-06 13:41 UTC, AyuAi approved these changes

2021-07-06 13:43 UTC, AyuAi commented
LGTM; We should probably merge sooner rather than later so we can continue off on #16 where Changsheng was commenting

2021-07-06 13:48 UTC, merged