AB#38602 error message mode switch
LokiLabs/microsoft-graph-explorer-v4 pull request #59
Opened 2021-08-04 21:59 UTC by lhao03

Shows different error messages for queries in app mode.
![Uploading screen-capture-_7_.gif…]()

2021-08-05 16:32 UTC, ChangshengYan approved these changes

2021-08-05 17:57 UTC, jerryxihe requested changes, later dismissed
![image](https://user-images.githubusercontent.com/46834951/128398209-bae5039a-f64c-41fd-b088-9dbf21eafd8e.png)

When I click the `GET my mail` sample query in user mode and then try to switch to app mode, it crashes in `determineErrorMessage()`

2021-08-06 00:30 UTC, lhao03 commented
> ![image](https://user-images.githubusercontent.com/46834951/128398209-bae5039a-f64c-41fd-b088-9dbf21eafd8e.png)
> 
> When I click the `GET my mail` sample query in user mode and then try to switch to app mode, it crashes in `determineErrorMessage()`

added missing undefined/null check https://github.com/LokiLabs/microsoft-graph-explorer-v4/pull/59/commits/60c13ac76743768501737acdc3501775704b7b95

2021-08-06 22:45 UTC, gracet9182 approved these changes
noice

2021-08-06 22:56 UTC, merged